function [DC, AC] = ZigZag(Co_Eff, block_X, block_Y)
	AC = zeros(block_X, block_Y, 63);
	DC = zeros(block_X, block_Y);
	
    % Use ZigZag for AC and and 1st co-eff for DC
    
	for blockNum_X=1:block_X
		r = (blockNum_X-1)*8;
		for blockNum_Y=1:block_Y
			c = (blockNum_Y-1)*8;
			
			AC(blockNum_X, blockNum_Y,:) = [...
								Co_Eff(r+1,c+2) Co_Eff(r+2,c+1) Co_Eff(r+3,c+1)...
                                Co_Eff(r+2,c+2) Co_Eff(r+1,c+3) Co_Eff(r+1,c+4)...
                                Co_Eff(r+2,c+3) Co_Eff(r+3,c+2) Co_Eff(r+4,c+1)...
                                Co_Eff(r+5,c+1) Co_Eff(r+4,c+2) Co_Eff(r+3,c+3)...
                                Co_Eff(r+2,c+4) Co_Eff(r+1,c+5) Co_Eff(r+1,c+6)...
                                Co_Eff(r+2,c+5) Co_Eff(r+3,c+4) Co_Eff(r+4,c+3)...
                                Co_Eff(r+5,c+2) Co_Eff(r+6,c+1) Co_Eff(r+7,c+1)...
                                Co_Eff(r+6,c+2) Co_Eff(r+5,c+3) Co_Eff(r+4,c+4)...
                                Co_Eff(r+3,c+5) Co_Eff(r+2,c+6) Co_Eff(r+1,c+7)...
                                Co_Eff(r+1,c+8) Co_Eff(r+2,c+7) Co_Eff(r+3,c+6)...
                                Co_Eff(r+4,c+5) Co_Eff(r+5,c+4) Co_Eff(r+6,c+3)...
                                Co_Eff(r+7,c+2) Co_Eff(r+8,c+1) Co_Eff(r+8,c+2)...
                                Co_Eff(r+7,c+3) Co_Eff(r+6,c+4) Co_Eff(r+5,c+5)...
                                Co_Eff(r+4,c+6) Co_Eff(r+3,c+7) Co_Eff(r+2,c+8)...
                                Co_Eff(r+3,c+8) Co_Eff(r+4,c+7) Co_Eff(r+5,c+6)...
                                Co_Eff(r+6,c+5) Co_Eff(r+7,c+4) Co_Eff(r+8,c+3)...
                                Co_Eff(r+8,c+4) Co_Eff(r+7,c+5) Co_Eff(r+6,c+6)...
                                Co_Eff(r+5,c+7) Co_Eff(r+4,c+8) Co_Eff(r+5,c+8)...
                                Co_Eff(r+6,c+7) Co_Eff(r+7,c+6) Co_Eff(r+8,c+5)...
                                Co_Eff(r+8,c+6) Co_Eff(r+7,c+7) Co_Eff(r+6,c+8)...
                                Co_Eff(r+7,c+8) Co_Eff(r+8,c+7) Co_Eff(r+8,c+8)];
		        DC(blockNum_X, blockNum_Y) = Co_Eff(r+1,c+1);
				
		end
	end
end